### ISSUE TITLE
How to create detail information about a patient of MedQA

### ISSUE THREAD

**Issue by Guangya2001** [SamuelSchmidgall/AgentClinic#1]
Hello, It's a surprising work! 
I'm very interested in the 107 patient information and how to create it. Did you use the GPT4 or just handcraft?
If using GPT4, I believe it would be very complex because medical record information such as test results and history can affect the final diagnosis. Would you share the method?

**Comment by SamuelSchmidgall** [comment]
All of the questions are based originally on MedQA questions and then expanded using GPT4 based on the diagnosis. You can prompt GPT4 using our OSCE template conditioning it on a particular diagnosis and case report so that it generates realistic cases. You should then go through and make sure everything seems reasonable by hand but otherwise GPT4 seems to do a good job.

**Comment by Guangya2001** [comment]
Thanks for your response！
